Repository andrewjswan/matrix-lamp, pull requests merged in 2025-09, with the labels that each got.

#56 Effect: Incremental Drift reborn
  components/matrix_lamp/__init__.py
  components/matrix_lamp/constants.h
  components/matrix_lamp/effect_ticker.h
  components/matrix_lamp/effects.h
Labels: bug, enhancement, small, stability/medium, effect

#59 Update documentation
  .mkdocs.yml
  docs/hardware.md
  docs/home-assistant.md
  docs/pin-scheme.md
Labels: documentation, small, stability/medium

#64 Add preset example package
  examples/preset/matrix_lamp_preset.yaml
Labels: documentation, enhancement, large, stability/medium

#65 Bump FastLED to 3.10.3
  components/matrix_lamp/__init__.py
  components/matrix_lamp/effects.h
Labels: enhancement, extra small, stability/medium, dependencies

#67 [matrix_lamp] Add preset and playlist management component
  examples/preset/README.md
  examples/preset/matrix_lamp_preset_playlist.yaml
Labels: enhancement, large, stability/medium
